services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - vectornet

  app:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    depends_on:
      - qdrant
      - db
    environment:
      QDRANT_URL: http://qdrant:6333
      DATABASE_URL: postgresql://devuser:devpass@db:5432/devdb
    networks:
      - vectornet
    command: sh -c "npx prisma migrate deploy && npm run dev"

  db:
    image: postgres:15
    container_name: local_pg
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - vectornet

networks:
  vectornet:
    driver: bridge
